### ISSUE TITLE
Redesign Form Builder - Figma

### ISSUE THREAD

**Issue by ErlingHauan** [ErlingHauan/FormFactory#41]
The current Form Builder interface creates some confusion, since the form components and save and validate buttons are grouped together. Create a new design where they are separated.

* Create desktop and mobile design in Figma
* Horizontal toolbar?
* The component settings should be a popup/modal in mobile view

**Comment by ErlingHauan** [comment]
Here are some suggestions for the new design. What do you think?
[Link to Figma board.](https://www.figma.com/file/DOc8uDcOuNze5pdogFKea1/Form-Factory?type=design&node-id=0%3A1&mode=design&t=ZBZPuz9pcc5umoWc-1)

Desktop:
![Image](https://github.com/ErlingHauan/FormFactory/assets/148075168/405f4b30-c835-41a3-93a6-9b1d4835203d)

Mobile:
![Image](https://github.com/ErlingHauan/FormFactory/assets/148075168/65141d9f-3905-42da-bd16-b31205eba4ec)

Mobile settings modal:
![Image](https://github.com/ErlingHauan/FormFactory/assets/148075168/cb78ae46-23e5-44a9-a0bc-20fe9db12618)

**Comment by lassopicasso** [comment]
Nice work! It looks great! 
Some thoughts:

- In component settings: maybe not necessary with radiobuttons, but just a checkbox for required. 
- The components position:
  two different approaches you may consider: 
  (1) In full width and mobile: keep the same position, but keep them in a dropdown menu.
  (2) In full width and mobile: keep them in a row below the header. But in full width, the row should still stay side by side with the settings container.  

Images for the second approach:

   
 Full width:
<img width="536" alt="image" src="https://github.com/ErlingHauan/FormFactory/assets/74791975/bf1e4c8b-eb65-41b7-9724-f38e5bda2ee1">

Mobile:
<img width="385" alt="image" src="https://github.com/ErlingHauan/FormFactory/assets/74791975/64d9adee-96e4-4e24-88c8-a46fdd36887c">

**Comment by ErlingHauan** [comment]
Something like this?

Desktop:
![image](https://github.com/ErlingHauan/FormFactory/assets/148075168/c5165cb5-f9be-4242-b534-37160c1ef7d4)

Mobile alternative 1:
![image](https://github.com/ErlingHauan/FormFactory/assets/148075168/748df79b-ad14-401b-bd6a-b228633ffea5)

Mobile alternative 2:
![image](https://github.com/ErlingHauan/FormFactory/assets/148075168/ade1f9f2-804a-469b-887b-1ca1fbeb926c)

**Comment by lassopicasso** [comment]
Nice! I like it, I think I would have chosen mobile alternative 1 :) What do you think @JamalAlabdullah ?

**Comment by lassopicasso** [comment]
What about mobile alternative 1, but where the save and publish button is not that dominant?

<img width="466" alt="image" src="https://github.com/ErlingHauan/FormFactory/assets/74791975/1b5a07ec-8a28-4732-ba3e-c230f63c5e51">

**Comment by JamalAlabdullah** [comment]
God job❤️ @ErlingHauan @lassopicasso 
just some thoughts;
- Do we need `Form Builder `tilte to be shown?
- What if we make somthing similer to AltinnStudio like a menu bar in the middle to show the content of our Form Factory.
- Maybe e can add a sub header for `save `and `publish`
- what if we put the draggable elements back to thier position (vertical ) because based on functionalty d&d it will be easer to drag and drop in horizintal way (in this case we avoid having an extra row ) (and we can find a way to make the lenght of vertical response with the length of the dropped area.

**Comment by ErlingHauan** [comment]
Thanks @JamalAlabdullah ❤️ 

Here's a new sketch based on your comments:
* Subheader added, with `save` and `publish` buttons, increasing separation of concerns.
* `Form Builder` title has been shrinked and moved to the side, making it less dominant.
* The draggable elements have been placed to the right, better utilizing the screen space. On mobile, we can perhaps move it back to the vertical position on top.

![image](https://github.com/ErlingHauan/FormFactory/assets/148075168/e3233a6b-b97b-475f-9147-9f5bd6458170)

**Comment by ErlingHauan** [comment]
Another option:
![image](https://github.com/ErlingHauan/FormFactory/assets/148075168/5170d827-1caf-4d03-9c63-9257e9c4a052)

**Comment by lassopicasso** [comment]
I really like that subheader! Would be nice to it in mobile viewport also. 

In desktop viewport perhaps we don't need to use the full width of the screen, but i.e. 1200px and lower the full width can be used. 
Not sure how it will look like, but narrow the width of Form builder area, but the keep subheader in full width.


![image](https://github.com/ErlingHauan/FormFactory/assets/74791975/a78aeb91-4016-4dd1-a474-136254904bda)
